export const CAMBIAR_IDIOMA = 'CAMBIAR_IDIOMA';
export const CAMBIAR_FILTRO = 'CAMBIAR_FILTRO';
export const CAMBIAR_MODO_REPASO = 'CAMBIAR_MODO_REPASO';
export const BUSCAR_CON_FILTRO = 'BUSCAR_CON_FILTRO';
export const DESCARGA_DICCIONARIO_OK = 'DESCARGA_DICCIONARIO_OK';
export const INICIO_DESCARGA_DICCIONARIO = 'INICIO_DESCARGA_DICCIONARIO';
export const GUARDADO_OK = 'GUARDADO_OK';
